# Generated by Django 3.1.3 on 2021-04-05 23:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
        ('cookbook', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='userProfile',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('savedCart', models.JSONField(blank=True)),
                ('favorites', models.ManyToManyField(to='cookbook.Recipe')),
            ],
        ),
    ]
