# Generated by Django 3.1.3 on 2021-04-07 01:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cookbook', '0002_auto_20210405_1642'),
        ('userPages', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userprofile',
            name='favorites',
            field=models.ManyToManyField(blank=True, to='cookbook.Recipe'),
        ),
        migrations.AlterField(
            model_name='userprofile',
            name='savedCart',
            field=models.JSONField(blank=True, null=True),
        ),
    ]
